### ISSUE TITLE
Menu desplegable de Tienda

### ISSUE THREAD

**Issue by Jonathan2693** [Mauriciods07/proyecto-integrador#83]
@AAtom02-A , el menu desplegable no tiene estilo similar a la tienda en ninguna de las paginas.
NOTA: Las modificaciones de estilo que se apliquen al menu deberan estar colocadas en su respectivo archivo CSS, osea el de pagina home

**Comment by AAtom02-A** [comment]
Ya modifique el sub menú despegable. 
Nota: falta hacer responsive.
